import "server-only";
import { images, type Img } from "@/content/images";
import type { Product, Tone } from "@/lib/commerce/types";

/*
 * Image registry access. The registry (with blur placeholders) is generated by
 * `scripts/process-images.mjs` and only ever read on the server; client components
 * receive the resolved `Img` objects they need as props.
 */

export type { Img };

const fallback: Img = { src: "/images/scenes/still-linen.jpg", w: 1600, h: 2000, blur: "", alt: "" };

export function img(key: string): Img {
  return images[key] ?? images[key.replace(/@.+$/, "")] ?? fallback;
}

export function productImg(p: Pick<Product, "images" | "name">, tone: Tone = "yellow"): Img {
  return images[`${p.images.hero}@${tone}`] ?? img(p.images.hero);
}

export const TONES: Tone[] = ["yellow", "white", "rose"];
