export type Faq = { q: string; a: string; topic: "Orders & shipping" | "Returns & sizing" | "Diamonds & materials" | "Engagement & bespoke" | "Care & warranty" };

export const faqs: Faq[] = [
  { topic: "Orders & shipping", q: "How long does shipping take?", a: "In-stock pieces ship in 1–2 business days and arrive 2–5 business days later by insured courier, signature required. Engagement rings and diamond bands are made to order in about two to three weeks; we send progress photos along the way." },
  { topic: "Orders & shipping", q: "Is shipping really free?", a: "Insured standard shipping is free on orders over $250 anywhere in the US. Under $250 it's $12. Express (2 days) and priority overnight are available at checkout." },
  { topic: "Orders & shipping", q: "Can I pick up my order in Dallas?", a: "Yes. Choose showroom pickup at checkout and we'll text you when it's ready, usually within one or two days. The showroom is in Knox-Henderson, off Henderson Avenue." },
  { topic: "Orders & shipping", q: "Do you ship outside the US?", a: "Not online yet. If you're abroad, email us: we've arranged insured international delivery for engagement rings on request." },
  { topic: "Returns & sizing", q: "What's your return policy?", a: "Return any unworn piece within 30 days for a full refund; return shipping is free and insured. Engraved, bespoke and builder rings are made just for you, so we resize or remake them instead of refunding." },
  { topic: "Returns & sizing", q: "What if the ring doesn't fit?", a: "Resizing is free within 60 days of delivery (most rings can go up or down two sizes). Not sure of your size? Order our free ring sizer and it arrives in a few days." },
  { topic: "Returns & sizing", q: "How do I find my ring size?", a: "Use our printable sizer, measure a ring you already own against our chart, or order a free plastic sizer. Fingers swell in the heat, so measure at the end of the day and choose the larger size if you're between two." },
  { topic: "Diamonds & materials", q: "Lab-grown or natural: what's the difference?", a: "Chemically, physically and optically they're the same: carbon in a cubic crystal. Lab-grown diamonds are made in weeks rather than mined, and cost a fraction of the price. Natural diamonds hold value better and carry the romance of age. We sell both and we'll show you side by side." },
  { topic: "Diamonds & materials", q: "Are your diamonds certified?", a: "Every centre stone over 0.5 ct comes with an independent grading report (GIA/IGI-style) for cut, colour, clarity and carat, and a laser inscription you can see under a loupe." },
  { topic: "Diamonds & materials", q: "Is your gold really recycled?", a: "Yes. All of our gold and platinum is refined from recycled sources and certified by our refiner. It's identical to newly mined metal, without the mining." },
  { topic: "Diamonds & materials", q: "Is sterling silver or plating used?", a: "A few entry pieces are made in solid sterling silver and clearly labelled. We never sell plated or filled pieces as gold: everything gold is solid 14k or 18k." },
  { topic: "Engagement & bespoke", q: "Can I see stones before you set them?", a: "Always. Come to the showroom and compare stones under daylight and candlelight, or book a video consultation and we'll send you videos of three candidates." },
  { topic: "Engagement & bespoke", q: "How does bespoke work and what does it cost?", a: "Tell us your idea and budget, and Margot sketches two or three directions within a week. Then we make a wax model you can try on, cast, set and polish. Most bespoke rings start around $2,500 and take four to six weeks." },
  { topic: "Engagement & bespoke", q: "Do you offer financing?", a: "Yes, 0% financing over 6 or 12 months is available on orders over $1,000, subject to approval. (Demo store: shown for illustration.)" },
  { topic: "Care & warranty", q: "What does the lifetime warranty cover?", a: "Manufacturing defects for life: loose stones from faulty settings, broken solder joints, clasp failures. It also includes free cleaning, polishing and prong checks whenever you visit." },
  { topic: "Care & warranty", q: "Do you repair jewelry you didn't make?", a: "Yes. Theo re-tips prongs, resizes, restrings pearls and repairs clasps for pieces from anywhere. Bring it in for a free assessment and a written quote." },
];
