import type { Product, Review } from "@/lib/commerce/types";

/*
 * The demo catalog. In a live store this file disappears and the same `Product`
 * shapes come from Shopify / Stripe through `src/lib/commerce`.
 */

const r = (name: string, city: string, rating: Review["rating"], date: string, title: string, body: string, variant?: string): Review => ({
  name,
  city,
  rating,
  date,
  title,
  body,
  variant,
});

const CARE_GOLD =
  "Solid gold doesn't tarnish, so wear it daily. Take it off for the gym and the pool (chlorine is hard on solder), and wipe it with the cloth in your box. Bring it to the showroom for a free ultrasonic clean and prong check any time.";
const CARE_STONE =
  "Diamonds love grease, so a quick soak in warm water with a drop of dish soap and a soft toothbrush brings the fire back. Book a free prong check once a year; we re-tip and re-polish under the lifetime warranty.";
const CARE_PEARL =
  "Pearls are the last thing on and the first thing off: after perfume and lotion, before the shower. Wipe with a soft dry cloth and store flat. Restringing is free for the first two years.";
const CARE_SILVER =
  "Sterling silver darkens a little with air; that's normal. The polishing cloth in your box restores it in seconds, and we'll give it a free professional polish any time you're in the showroom.";

export const products: Product[] = [
  /* ------------------------------------------------------------------ RINGS */
  {
    slug: "lume-signet",
    name: "Lume Signet",
    category: "rings",
    price: 1250,
    sku: "AL-R-101",
    metals: ["14k-yellow", "14k-white", "14k-rose", "18k-yellow"],
    ringSizes: true,
    stone: "none",
    short: "A round signet with a hand-chased relief on its face. Or leave it blank for your own initial or crest.",
    long: [
      "The Lume is the ring Margot designed for herself in 2014, and still the one most people ask about. The 11 mm face carries a small relief that our engraver chases by hand, so the light pools in it.",
      "It's cast in recycled gold, then filed and polished by hand so the shoulders flow into the band without a seam. Leave it plain, or have our engraver cut an initial, a date or a family crest into the face.",
    ],
    specs: [["Metal", "Recycled solid gold"], ["Face", "11 mm round, hand-chased relief"], ["Band", "2.6 mm tapering to 2 mm"], ["Weight", "≈ 6.2 g in 14k, size 6"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    badges: ["bestseller"],
    collections: ["bestsellers", "everyday-gold"],
    pairs: ["thread-ring", "paperclip-chain", "dune-hoops"],
    rating: 4.9,
    reviewCount: 128,
    reviews: [
      r("Hannah R.", "Highland Park", 5, "2026-08-14", "Heirloom feel, everyday comfort", "Bought it for my husband's 40th and had his grandfather's initials engraved. It looks like it's been in the family for decades, in the best way. He hasn't taken it off.", "14k Yellow Gold · Size 10"),
      r("Marcus T.", "Lakewood", 5, "2026-06-02", "Weight is perfect", "Heavier than it looks in photos, which I wanted. Sizing was spot on after the free sizer they mailed me."),
      r("Elise W.", "Austin", 4, "2026-03-19", "Beautiful, took a little longer", "Engraving added four days, which they warned me about. The finish is flawless.", "14k Rose Gold · Size 5.5"),
    ],
    images: { hero: "lume-signet-1", model: "lume-signet-2" },
    scaleMm: 11,
    added: "2025-02-10",
  },
  {
    slug: "thread-ring",
    name: "Thread Stacking Ring",
    category: "rings",
    price: 240,
    sku: "AL-R-102",
    metals: ["14k-rose", "14k-yellow", "14k-white"],
    ringSizes: true,
    stone: "none",
    short: "A 1.2 mm band of solid gold, round in profile, made to be stacked in threes.",
    long: [
      "Thread is the quietest ring we make: a fine round wire of solid gold, closed with a laser weld you will never find. Wear one alone or build a stack in mixed metals.",
      "Because it's solid gold rather than plated, it won't wear through to another colour, and we can resize it for free in the first 60 days.",
    ],
    specs: [["Metal", "Recycled solid gold"], ["Width", "1.2 mm round wire"], ["Finish", "High polish"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    badges: ["bestseller"],
    collections: ["bestsellers", "everyday-gold", "gift-edit"],
    pairs: ["lume-signet", "meridian-pave", "fine-id-bracelet"],
    rating: 4.8,
    reviewCount: 96,
    reviews: [
      r("Priya S.", "Plano", 5, "2026-09-01", "Bought three", "One of each metal. They sit together like they were cast as a set. Thinner than my old ones but they haven't bent at all."),
      r("Jordan K.", "Uptown", 5, "2026-07-11", "Perfect first piece of real gold", "Gift to myself after a promotion. The box and the handwritten note made it feel like a much bigger purchase.", "14k Yellow Gold · Size 6"),
    ],
    images: { hero: "thread-ring-1", model: "thread-ring-2" },
    scaleMm: 1.2,
    added: "2025-04-01",
  },
  {
    slug: "ember-wave",
    name: "Ember Wave Ring",
    category: "rings",
    price: 890,
    sku: "AL-R-103",
    metals: ["14k-yellow", "14k-rose", "18k-yellow"],
    ringSizes: true,
    stone: "none",
    short: "A bold, molten wave of gold that looks poured rather than made, hollowed inside so it wears lighter than it looks.",
    long: [
      "Ember is carved in wax first, by hand, so no two waves are quite identical. It rises to 9 mm at the top and tapers underneath, so it sits comfortably between other fingers.",
      "We hollow the inside to keep the weight wearable, then polish every ripple to a deep, liquid shine that throws long reflections.",
    ],
    specs: [["Metal", "Recycled solid gold"], ["Top width", "9 mm, tapering to 4 mm"], ["Profile", "Hand-carved wave, hollow-backed"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    badges: ["new"],
    collections: ["new-in", "everyday-gold"],
    pairs: ["thread-ring", "dune-hoops", "olive-branch-cuff"],
    rating: 4.9,
    reviewCount: 31,
    reviews: [
      r("Camila V.", "Bishop Arts", 5, "2026-09-12", "Statement without shouting", "Gets compliments constantly. It's chunky but not heavy, I forget it's there.", "14k Yellow Gold · Size 7"),
      r("Dana P.", "Fort Worth", 5, "2026-08-30", "Better in person", "The polish is unreal. It reflects the whole room."),
    ],
    images: { hero: "ember-dome-1", model: "ember-dome-2" },
    scaleMm: 9,
    added: "2026-09-02",
  },
  {
    slug: "meridian-pave",
    name: "Meridian Pavé Duo",
    category: "rings",
    price: 1450,
    sku: "AL-R-104",
    metals: ["14k-yellow", "14k-white", "14k-rose", "platinum"],
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 650,
    stone: "diamond",
    short: "An open double band: a row of pavé diamonds above, a beaded band and a single stone below.",
    long: [
      "Meridian carries a line of 1.5 mm diamonds on its upper band and a single round stone at the end of a hand-beaded lower band, so it looks like two rings stacked.",
      "The open design gives a little flex, which makes it comfortable all day. Wear it alone or as the start of a stack.",
    ],
    specs: [["Stones", "11 × 1.5 mm round, ≈ 0.18 ct total"], ["Quality", "F–G colour, VS clarity"], ["Band", "2 mm"], ["Setting", "Hand-raised micro pavé"], ["Report", "Independently graded (GIA/IGI-style) on request"]],
    care: CARE_STONE,
    badges: ["bestseller"],
    collections: ["bestsellers", "bridal"],
    pairs: ["thread-ring", "glint-studs", "ardley-solitaire"],
    rating: 4.9,
    reviewCount: 74,
    reviews: [
      r("Ashley N.", "Preston Hollow", 5, "2026-05-20", "Wedding band I actually love", "Looks like a whole stack on its own. They let me try it with my solitaire in the showroom before ordering.", "Platinum · Lab-grown stone · Size 6"),
      r("Ben O.", "Frisco", 5, "2026-04-08", "Anniversary win", "The sparkle under restaurant lights is ridiculous. Wife cried. Ten out of ten."),
      r("Lauren M.", "Dallas", 4, "2026-02-14", "Gorgeous, size runs true", "I was between sizes and went down, which was right. Lovely packaging."),
    ],
    images: { hero: "meridian-pave-1", model: "meridian-pave-2" },
    scaleMm: 2,
    added: "2025-06-15",
  },
  {
    slug: "solene-emerald",
    name: "Solène Emerald Ring",
    category: "rings",
    price: 1350,
    sku: "AL-R-105",
    metals: ["14k-yellow", "18k-yellow", "platinum"],
    ringSizes: true,
    stone: "emerald",
    short: "A slim green emerald baguette between two tiny diamonds, on a fine gold band.",
    long: [
      "Margot chose this lot of emeralds for their colour: a cool, saturated green that stays rich even in low light. Each baguette is lightly oiled, as almost all fine emeralds are.",
      "The emerald sits east-to-west in a low setting with a diamond at each end, slim enough to stack with a wedding band.",
    ],
    specs: [["Centre", "≈ 0.35 ct emerald baguette"], ["Accents", "2 round diamonds"], ["Treatment", "Traditional minor oil"], ["Band", "1.5 mm"], ["Made in", "Dallas, TX"]],
    care: "Emeralds are tougher on colour than on hardness: avoid ultrasonic cleaners and hot water. Wipe with a damp cloth and bring it in for a free claw check once a year.",
    sale: 0.2,
    collections: ["on-sale"],
    pairs: ["thread-ring", "pearl-drops", "fine-id-bracelet"],
    rating: 4.8,
    reviewCount: 22,
    reviews: [
      r("Nadia F.", "University Park", 5, "2026-07-02", "That green", "Photos don't do the colour justice. It looks almost black in candlelight and glows in the sun.", "18k Yellow Gold · Size 6"),
      r("Grace L.", "Houston", 5, "2026-05-15", "Birthstone, done right", "I wanted green for my birthstone. Margot walked me through emerald care on a video call before I bought."),
    ],
    images: { hero: "solene-emerald-1", model: "solene-emerald-2" },
    scaleMm: 8,
    added: "2025-09-20",
  },
  {
    slug: "dusk-sapphire",
    name: "Dusk Sapphire Bypass",
    category: "rings",
    price: 760,
    sku: "AL-R-106",
    metals: ["14k-yellow", "14k-white", "platinum"],
    ringSizes: true,
    stone: "sapphire",
    short: "An open bypass ring: a deep blue sapphire at one end, a single diamond at the other, like the first star at dusk.",
    long: [
      "The sapphire is a 3 mm round in a deep, velvety blue, bezel-set across from a 3 mm diamond. The band is a fine 1.3 mm wire that wraps past itself.",
      "Sapphire is hard enough to wear every day for a lifetime, which makes this a favourite for September birthdays and anniversaries.",
    ],
    specs: [["Stones", "3 mm blue sapphire, 3 mm diamond"], ["Setting", "Bezel"], ["Band", "1.3 mm bypass"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    collections: ["bridal"],
    pairs: ["glint-studs", "meridian-pave", "onyx-station"],
    rating: 4.9,
    reviewCount: 18,
    reviews: [
      r("Olivia C.", "Lakewood", 5, "2026-08-21", "Something blue", "Bought as my 'something blue' and now wear it every day on my right hand.", "Platinum · Size 5"),
      r("Ethan J.", "Denton", 5, "2026-01-30", "Great colour", "Dainty, but the sapphire colour is so rich. Perfect birthday gift."),
    ],
    images: { hero: "dusk-sapphire-1", model: "dusk-sapphire-2" },
    scaleMm: 7,
    added: "2025-11-04",
  },
  {
    slug: "seed-pearl-bands",
    name: "Seed Pearl Bands",
    category: "rings",
    price: 420,
    sku: "AL-R-107",
    metals: ["14k-yellow", "sterling"],
    metalDelta: { sterling: -240 },
    ringSizes: true,
    stone: "pearl",
    short: "A pair of slim bands set all the way round with tiny seed pearls. Wear them together or split the set.",
    long: [
      "Each band carries thirty-odd 1.5 mm seed pearls, matched for lustre and set in a channel so they can't catch. Sold as a pair: one for you, one for someone else, if you like.",
      "In solid gold it's an heirloom; in sterling it's our most popular first gift.",
    ],
    specs: [["Pearls", "≈ 64 × 1.5 mm seed pearls (pair)"], ["Band", "2 mm each, channel set"], ["Sold as", "A pair of bands"], ["Made in", "Dallas, TX"]],
    care: CARE_PEARL,
    collections: ["gift-edit"],
    pairs: ["pearl-drops", "pearl-strand", "thread-ring"],
    rating: 4.7,
    reviewCount: 44,
    reviews: [
      r("Mia H.", "Richardson", 5, "2026-06-12", "Sweetest gift", "Got the pair for my daughter's graduation and she gave one to her best friend. The pearls are a lovely creamy white.", "Sterling Silver · Size 5"),
      r("Sofia R.", "Irving", 4, "2026-03-03", "Delicate", "Beautiful and comfortable. I take it off to wash my hands, as they recommend."),
    ],
    images: { hero: "twin-pearl-1", model: "twin-pearl-2" },
    scaleMm: 2,
    added: "2025-08-01",
  },

  /* ----------------------------------------------------------- ENGAGEMENT */
  {
    slug: "ardley-solitaire",
    name: "The Ardley Solitaire",
    category: "engagement",
    price: 3900,
    sku: "AL-E-201",
    metals: ["platinum", "14k-yellow", "14k-white", "18k-yellow"],
    metalDelta: { platinum: 0, "14k-yellow": -350, "14k-white": -350, "18k-yellow": -100 },
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 5400,
    stone: "diamond",
    short: "A 1 ct round brilliant held by six slim claws on a 1.8 mm band. The ring we're known for.",
    long: [
      "The Ardley is the cleanest way we know to hold a diamond: six claws, tapered so they disappear from the front, a gallery that lets light in from the side, and a band that narrows slightly toward the stone.",
      "Price shown is for a 1.0 ct lab-grown round, F colour, VS1 clarity, excellent cut. Choose natural for a mined, independently graded stone; we'll send you videos of three candidates before setting.",
    ],
    specs: [["Centre", "1.0 ct round brilliant"], ["Grade", "F / VS1 / Excellent (lab) · G / VS1 / Excellent (natural)"], ["Setting", "Six-claw, open gallery"], ["Band", "1.8 mm, comfort fit"], ["Report", "Independently graded (GIA/IGI-style)"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    badges: ["bestseller"],
    collections: ["bestsellers", "bridal"],
    pairs: ["companion-band", "classic-band", "glint-studs"],
    rating: 5,
    reviewCount: 141,
    reviews: [
      r("Daniel & Kim", "Highland Park", 5, "2026-09-05", "She said yes in Klyde Warren Park", "They let me compare four stones side by side under different lights. I chose the second one, and I'd choose it again. The setting is impossibly delicate but feels solid.", "Platinum · Lab-grown stone · Size 5.5"),
      r("Tyler B.", "Plano", 5, "2026-07-19", "No pressure, all patience", "Three visits, zero hard sell. Theo explained cut grades with a loupe and a sketchpad."),
      r("Rachel G.", "Chicago", 5, "2026-04-27", "Ordered online from Illinois", "Video consultation, stone videos, insured overnight delivery. Ring arrived in the most beautiful box."),
    ],
    images: { hero: "ardley-solitaire-1", model: "ardley-solitaire-2" },
    scaleMm: 6.4,
    added: "2024-11-01",
  },
  {
    slug: "celeste-oval-halo",
    name: "Celeste Oval Halo",
    category: "engagement",
    price: 4800,
    sku: "AL-E-202",
    metals: ["platinum", "14k-white", "14k-yellow", "14k-rose"],
    metalDelta: { platinum: 0, "14k-white": -400, "14k-yellow": -400, "14k-rose": -400 },
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 6200,
    stone: "diamond",
    short: "A 1.5 ct oval framed by a fine halo of micro-pavé, on a band set halfway down.",
    long: [
      "An oval reads larger than a round of the same weight, and a halo of 0.2 mm-thin claws makes it look larger still. Celeste keeps the halo tight so the centre stays the hero.",
      "Price is for a 1.5 ct lab oval, F/VS1, with a 1.4–1.5 length-to-width ratio. Natural stones are sourced to order and sent to you on video first.",
    ],
    specs: [["Centre", "1.5 ct oval"], ["Halo & band", "≈ 0.35 ct micro-pavé"], ["Grade", "F / VS1 (lab) · G / VS2 (natural)"], ["Band", "1.7 mm"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    collections: ["bridal"],
    pairs: ["eternity-band", "companion-band", "glint-studs"],
    rating: 4.9,
    reviewCount: 63,
    reviews: [
      r("Brianna T.", "Frisco", 5, "2026-08-08", "Looks like 2 carats", "Everyone guesses it's bigger than it is. The halo is so fine it almost disappears.", "Platinum · Lab-grown stone · Size 6"),
      r("Chris D.", "Arlington", 5, "2026-05-02", "Great experience", "Booked an appointment on a Saturday, left with a plan and a quote in writing. No surprises."),
    ],
    images: { hero: "celeste-oval-halo-1", model: "celeste-oval-halo-2" },
    scaleMm: 10,
    added: "2025-01-15",
  },
  {
    slug: "trinity-three-stone",
    name: "Trinity Cluster Ring",
    category: "engagement",
    price: 4600,
    sku: "AL-E-203",
    metals: ["platinum", "14k-yellow", "14k-white"],
    metalDelta: { platinum: 0, "14k-yellow": -450, "14k-white": -450 },
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 3900,
    stone: "diamond",
    short: "Three illusion-set diamond clusters in a row: past, present and future, with the sparkle of a much larger stone.",
    long: [
      "Each of Trinity's three heads is a flower of seven diamonds, set in white gold so they read as three larger stones. The gallery sits low, so it stays comfortable against a wedding band.",
      "We match all twenty-one stones for colour under daylight and showroom light. A lovely way to get presence without a single large centre.",
    ],
    specs: [["Stones", "21 round diamonds in 3 clusters"], ["Total", "≈ 1.0 ct"], ["Setting", "Illusion clusters, white-gold heads"], ["Band", "2 mm"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    badges: ["new"],
    collections: ["new-in", "bridal"],
    pairs: ["classic-band", "pearl-drops", "tennis-bracelet"],
    rating: 5,
    reviewCount: 19,
    reviews: [
      r("Michael A.", "Lake Highlands", 5, "2026-09-18", "For our tenth", "We added Trinity for our tenth anniversary. Three clusters for three kids. It sparkles like crazy.", "Platinum · Natural stone · Size 6.5"),
      r("Jasmine W.", "Garland", 5, "2026-09-02", "Breathtaking", "Low profile, catches my sweaters less than my old ring. Gorgeous."),
    ],
    images: { hero: "trinity-three-stone-1", model: "trinity-three-stone-2" },
    scaleMm: 13,
    added: "2026-08-25",
  },
  {
    slug: "margot-emerald-cut",
    name: "Margot Emerald-Cut",
    category: "engagement",
    price: 7400,
    sku: "AL-E-204",
    metals: ["platinum", "18k-yellow", "14k-white"],
    metalDelta: { platinum: 0, "18k-yellow": -200, "14k-white": -500 },
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 9800,
    stone: "diamond",
    short: "A 2 ct emerald-cut in four double claws: long, quiet mirrors of light instead of sparkle.",
    long: [
      "Step-cut diamonds show their clarity, so we only set emerald cuts of VS1 or better. The result is the 'hall of mirrors' effect: broad flashes of light rather than glitter.",
      "Margot designed the double claws so each corner is protected, and the band is a touch wider to balance the length of the stone.",
    ],
    specs: [["Centre", "2.0 ct emerald cut"], ["Grade", "E / VS1 (lab) · F / VS1 (natural)"], ["Setting", "Four double claws"], ["Band", "2 mm"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    collections: ["bridal"],
    pairs: ["knife-edge-band", "glint-studs", "lume-pendant"],
    rating: 5,
    reviewCount: 37,
    reviews: [
      r("Victoria S.", "Turtle Creek", 5, "2026-06-30", "Old Hollywood", "Exactly the vintage look I wanted, made new. The clarity is stunning.", "Platinum · Lab-grown stone · Size 5"),
      r("James H.", "Southlake", 5, "2026-03-22", "Worth every visit", "Margot herself sketched the claws with us. Felt like commissioning art."),
    ],
    images: { hero: "margot-emerald-cut-1", model: "margot-emerald-cut-2" },
    scaleMm: 9,
    added: "2025-03-12",
  },
  {
    slug: "dewdrop-pear",
    name: "Dewdrop Pear Halo",
    category: "engagement",
    price: 3600,
    sku: "AL-E-205",
    metals: ["platinum", "14k-white"],
    metalDelta: { platinum: 380, "14k-white": 0 },
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 4300,
    stone: "diamond",
    short: "A 1 ct pear inside a halo of round diamonds, with pavé running down the shoulders.",
    long: [
      "The halo is set with fourteen round diamonds whose claws also guard the fragile point of the pear, so it's as practical as it is bright.",
      "Price is for a 1.0 ct lab pear, F/VS1. Wear the point toward the fingertip to lengthen the hand, or toward the wrist for a romantic, vintage look.",
    ],
    specs: [["Centre", "1.0 ct pear"], ["Halo & shoulders", "≈ 0.45 ct round"], ["Band", "2 mm"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    sale: 0.15,
    collections: ["on-sale", "bridal"],
    pairs: ["companion-band", "lume-pendant", "glint-studs"],
    rating: 4.9,
    reviewCount: 28,
    reviews: [
      r("Kayla M.", "Oak Cliff", 5, "2026-07-24", "Bright and secure", "The halo makes the pear look enormous, and the point feels completely protected. Sparkles across the room.", "Platinum · Lab-grown stone · Size 6"),
      r("Andrew P.", "Dallas", 5, "2026-04-11", "Sale sample, zero compromise", "Bought the showroom sample on sale; it was re-polished and sized and looked brand new."),
    ],
    images: { hero: "dewdrop-pear-1", model: "dewdrop-pear-2" },
    scaleMm: 9,
    added: "2025-05-05",
  },
  {
    slug: "aurora-hidden-halo",
    name: "Aurora Hidden Halo",
    category: "engagement",
    price: 9800,
    sku: "AL-E-206",
    metals: ["platinum", "18k-yellow"],
    metalDelta: { platinum: 0, "18k-yellow": 0 },
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 14500,
    stone: "diamond",
    short: "A 3 ct centre with a secret halo under the stone, visible only from the side.",
    long: [
      "From above, Aurora is a pure solitaire. Turn your hand and a ring of tiny diamonds appears beneath the centre, like light under a door.",
      "Price is for a 3.0 ct lab round, E/VS1, excellent cut. Every Aurora is made to order in about three weeks, with a progress photo at each stage.",
    ],
    specs: [["Centre", "3.0 ct round brilliant"], ["Hidden halo", "≈ 0.15 ct micro-pavé"], ["Grade", "E / VS1 / Excellent"], ["Band", "2 mm, pavé shoulders"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    collections: ["bridal"],
    pairs: ["eternity-band", "tennis-bracelet", "glint-studs"],
    rating: 5,
    reviewCount: 14,
    reviews: [
      r("Stephanie L.", "Preston Hollow", 5, "2026-08-02", "The hidden halo is everything", "I love that it's a secret. From the side it's magic.", "Platinum · Lab-grown stone · Size 6"),
      r("Robert K.", "Westlake", 5, "2026-02-19", "White-glove from start to finish", "Progress photos at every stage. Delivered by hand to our office."),
    ],
    images: { hero: "aurora-hidden-halo-1", model: "aurora-hidden-halo-2" },
    scaleMm: 9.3,
    added: "2025-10-10",
  },

  /* -------------------------------------------------------- WEDDING BANDS */
  {
    slug: "classic-band",
    name: "Classic Comfort Band",
    category: "wedding-bands",
    price: 680,
    sku: "AL-W-301",
    metals: ["14k-yellow", "14k-white", "14k-rose", "18k-yellow", "platinum"],
    ringSizes: true,
    stone: "none",
    short: "The forever band: a softly domed 4 mm profile with a comfort-fit interior.",
    long: [
      "A comfort-fit band is rounded on the inside as well as the outside, so it slides over the knuckle and never pinches. Ours is 4 mm wide and 1.6 mm thick: substantial without being heavy.",
      "Add a hidden engraving inside for $45; we cut it by hand, not by laser.",
    ],
    specs: [["Width", "4 mm (3 and 5 mm on request)"], ["Profile", "Domed, comfort fit"], ["Thickness", "1.6 mm"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    badges: ["bestseller"],
    collections: ["bestsellers", "bridal", "everyday-gold"],
    pairs: ["ardley-solitaire", "forge-band", "lume-signet"],
    rating: 4.9,
    reviewCount: 117,
    reviews: [
      r("Sam & Leo", "Oak Lawn", 5, "2026-06-28", "Matching bands", "We got one in yellow and one in platinum, with each other's handwriting engraved inside. They traced it from our vows.", "Platinum · Size 9"),
      r("Megan D.", "McKinney", 5, "2026-05-10", "So comfortable", "Didn't know comfort fit was a thing. Never going back."),
    ],
    images: { hero: "classic-band-1", model: "classic-band-2" },
    scaleMm: 4,
    added: "2024-10-01",
  },
  {
    slug: "knife-edge-band",
    name: "Knife-Edge Band",
    category: "wedding-bands",
    price: 720,
    sku: "AL-W-302",
    metals: ["14k-yellow", "14k-white", "platinum"],
    ringSizes: true,
    stone: "none",
    short: "A 2 mm band with a fine ridge along the top that catches a single line of light.",
    long: [
      "Knife-edge bands look slimmer than they are: the peak throws one bright line while the sides fall into shadow. Ours pairs beautifully with emerald cuts and other step-cut stones.",
      "Hand-finished and checked for symmetry under magnification before it leaves the bench.",
    ],
    specs: [["Width", "2 mm"], ["Profile", "Knife edge"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    collections: ["bridal"],
    pairs: ["margot-emerald-cut", "thread-ring", "classic-band"],
    rating: 4.8,
    reviewCount: 39,
    reviews: [
      r("Allison J.", "Uptown", 5, "2026-04-30", "Sleek", "Looks like a line of light next to my emerald cut. Exactly what I hoped.", "Platinum · Size 5"),
      r("Peter N.", "Coppell", 4, "2026-01-12", "Elegant", "Lovely band, took one resize which they did free within the week."),
    ],
    images: { hero: "knife-edge-band-1", model: "knife-edge-band-2" },
    scaleMm: 2,
    added: "2025-02-01",
  },
  {
    slug: "eternity-band",
    name: "Lumière Eternity Band",
    category: "wedding-bands",
    price: 2400,
    sku: "AL-W-303",
    metals: ["platinum", "14k-white"],
    metalDelta: { platinum: 0, "14k-white": -200 },
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 2100,
    stone: "diamond",
    short: "A full circle of 2.2 mm diamonds in shared claws: about one carat, all the way round.",
    long: [
      "Eternity bands are made to size, because the stones go all the way around. We count the stones for your exact finger, so the spacing is perfect and the diamonds meet without a gap.",
      "Price shown is for size 6 in lab diamonds (≈ 1.0 ct total). Sizes above 7 add one or two stones; we'll confirm before making.",
    ],
    specs: [["Stones", "≈ 22 × 2.2 mm round, ≈ 1.0 ct"], ["Quality", "F–G / VS"], ["Setting", "Shared claw, full eternity"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    badges: ["bestseller"],
    collections: ["bestsellers", "bridal"],
    pairs: ["celeste-oval-halo", "aurora-hidden-halo", "tennis-bracelet"],
    rating: 4.9,
    reviewCount: 58,
    reviews: [
      r("Natalie B.", "Highland Park", 5, "2026-08-17", "Pure light", "It sparkles from every angle, even on the underside. Perfect with my oval.", "Platinum · Lab-grown stone · Size 6"),
      r("Kevin R.", "Plano", 5, "2026-03-28", "Push present", "Worth it. The note in the box made her laugh and cry."),
    ],
    images: { hero: "eternity-band-1", model: "eternity-band-2" },
    scaleMm: 2.2,
    added: "2024-12-12",
  },
  {
    slug: "forge-band",
    name: "Forge Grooved Band",
    category: "wedding-bands",
    price: 890,
    sku: "AL-W-304",
    metals: ["14k-yellow", "14k-white", "18k-yellow", "platinum"],
    ringSizes: true,
    stone: "none",
    short: "A wide, flat 6 mm band with stepped, grooved edges: architectural, substantial, quietly modern.",
    long: [
      "Forge is turned and then hand-finished so the two stepped grooves at the edges stay crisp while the centre stays bright. It's our most-requested men's band.",
      "The inside is polished smooth and comfort-fit; the edges are softly rounded so it never digs in.",
    ],
    specs: [["Width", "6 mm"], ["Edges", "Stepped double groove"], ["Profile", "Flat, comfort fit"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    sale: 0.2,
    collections: ["on-sale", "bridal"],
    pairs: ["classic-band", "knot-link", "lume-signet"],
    rating: 4.8,
    reviewCount: 46,
    reviews: [
      r("Diego M.", "East Dallas", 5, "2026-07-07", "Built for my job", "I'm a mechanic. Six months in, it still looks sharp. The grooves are a great detail.", "14k Yellow Gold · Size 11"),
      r("Chris T.", "Grapevine", 5, "2026-02-25", "Unique", "Heavy in the best way. My wife chose the matching pair."),
    ],
    images: { hero: "hammered-band-1", model: "hammered-band-2" },
    scaleMm: 6,
    added: "2025-07-07",
  },
  {
    slug: "companion-band",
    name: "Companion Pavé Band",
    category: "wedding-bands",
    price: 1150,
    sku: "AL-W-305",
    metals: ["14k-white", "platinum"],
    ringSizes: true,
    stones: ["lab", "natural"],
    naturalDelta: 450,
    stone: "diamond",
    short: "A slim pavé band built to sit flush beside a raised engagement ring, with no gap between them.",
    long: [
      "Companion is fitted at the bench to your engagement ring. Send us yours (insured, prepaid) or bring it in, and we'll adjust the height and profile so the two sit flush.",
      "Small diamonds run across the top half. Bought with an Ardley & Lume engagement ring, the fitting is already done.",
    ],
    specs: [["Stones", "11 × 1.6 mm, ≈ 0.2 ct"], ["Width", "1.8 mm"], ["Fit", "Fitted flush to your ring"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    collections: ["bridal"],
    pairs: ["ardley-solitaire", "dewdrop-pear", "celeste-oval-halo"],
    rating: 4.9,
    reviewCount: 33,
    reviews: [
      r("Erin S.", "Lakewood", 5, "2026-09-09", "Finally flush", "My engagement ring is from elsewhere, and they still made the band fit like it was one piece.", "Platinum · Lab-grown stone · Size 6"),
      r("Hailey G.", "Frisco", 5, "2026-06-14", "So pretty stacked", "They look like one piece. So flattering."),
    ],
    images: { hero: "contour-band-1", model: "contour-band-2" },
    scaleMm: 1.8,
    added: "2025-08-20",
  },

  /* ------------------------------------------------------------- EARRINGS */
  {
    slug: "glint-studs",
    name: "Glint Diamond Studs",
    category: "earrings",
    price: 580,
    sku: "AL-A-401",
    metals: ["14k-yellow", "14k-white", "14k-rose", "platinum"],
    stones: ["lab", "natural"],
    naturalDelta: 900,
    stone: "diamond",
    short: "Half a carat total of round diamonds in smooth bezels, with screw backs.",
    long: [
      "Every pair of Glint studs is matched by eye under daylight: same colour, same size, same sparkle. The bezels are slim so the stones sit close to the ear.",
      "Screw backs come standard, because a diamond stud should never be a worry.",
    ],
    specs: [["Stones", "2 × 0.25 ct round"], ["Quality", "F–G / VS"], ["Backs", "Screw back"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    badges: ["bestseller"],
    collections: ["bestsellers", "bridal"],
    pairs: ["ardley-solitaire", "lume-pendant", "tennis-bracelet"],
    rating: 4.9,
    reviewCount: 104,
    reviews: [
      r("Lena K.", "Uptown", 5, "2026-08-26", "Wear them 24/7", "Sleep, shower, gym. Screw backs never budge.", "14k White Gold · Lab-grown stone"),
      r("Tom W.", "Rockwall", 5, "2026-05-12", "Mother's Day hit", "My mom calls them her 'forever earrings'."),
    ],
    images: { hero: "glint-studs-1", model: "glint-studs-2" },
    scaleMm: 4.1,
    added: "2024-11-20",
  },
  {
    slug: "halo-hoops",
    name: "Halo Hoops",
    category: "earrings",
    price: 390,
    sku: "AL-A-402",
    metals: ["14k-yellow", "14k-white", "14k-rose"],
    stone: "none",
    short: "Small 14 mm hoops in solid gold, rounded tube, hinged click closure.",
    long: [
      "Our most-gifted earrings. The tube is 2 mm, rounded, and hollow enough to be featherlight, with a hinged closure that clicks shut with confidence.",
      "Small enough for a second piercing, bold enough on their own.",
    ],
    specs: [["Diameter", "14 mm"], ["Tube", "2 mm round"], ["Closure", "Hinged click"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    badges: ["bestseller"],
    collections: ["bestsellers", "gift-edit", "everyday-gold"],
    pairs: ["sculpted-huggies", "paperclip-chain", "thread-ring"],
    rating: 4.8,
    reviewCount: 136,
    reviews: [
      r("Ava B.", "Deep Ellum", 5, "2026-09-14", "Never taking them off", "The click closure is so satisfying. Feels like real quality.", "14k Yellow Gold"),
      r("Isabella F.", "Plano", 5, "2026-06-01", "Gift for my sister", "Gift wrap was stunning, and she loved them."),
    ],
    images: { hero: "halo-hoops-1", model: "halo-hoops-2" },
    scaleMm: 14,
    added: "2025-01-05",
  },
  {
    slug: "sculpted-huggies",
    name: "Sculpted Huggies",
    category: "earrings",
    price: 320,
    sku: "AL-A-403",
    metals: ["14k-yellow", "14k-rose", "sterling"],
    metalDelta: { sterling: -180 },
    stone: "none",
    short: "Chunky little huggies that sit snug to the lobe, 10 mm across with a sculpted, organic edge.",
    long: [
      "Huggies are the earrings you forget you're wearing: short posts, a snug fit and a hinge that closes flush.",
      "Ours are carved in wax first, so the surface has a subtle, hand-made wave that catches light from every angle.",
    ],
    specs: [["Diameter", "10 mm"], ["Width", "4 mm"], ["Closure", "Hinged"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    badges: ["new"],
    collections: ["new-in", "gift-edit", "everyday-gold"],
    pairs: ["halo-hoops", "constellation-climbers", "ember-wave"],
    rating: 4.8,
    reviewCount: 27,
    reviews: [
      r("Zoe T.", "Bishop Arts", 5, "2026-09-20", "Instant favourite", "Bold but tiny. Great for every day.", "14k Yellow Gold"),
      r("Leah N.", "Arlington", 4, "2026-09-03", "Love them", "The sterling ones are a great price. Planning the gold next."),
    ],
    images: { hero: "sculpted-huggies-1", model: "sculpted-huggies-2" },
    scaleMm: 10,
    added: "2026-09-10",
  },
  {
    slug: "pearl-drops",
    name: "Pearl Drops",
    category: "earrings",
    price: 460,
    sku: "AL-A-404",
    metals: ["14k-yellow", "14k-white"],
    stone: "pearl",
    short: "Lustrous 8 mm freshwater pearls that swing from a small gold hoop.",
    long: [
      "We buy pearls in small lots so we can match pairs for lustre and overtone. These have a soft rosé glow that flatters every skin tone.",
      "The hoops are solid gold and detachable, so you can wear them alone too.",
    ],
    specs: [["Pearls", "2 × 8 mm freshwater, AAA"], ["Drop", "24 mm"], ["Closure", "Detachable hoop"], ["Made in", "Dallas, TX"]],
    care: CARE_PEARL,
    collections: ["bridal", "gift-edit"],
    pairs: ["pearl-strand", "seed-pearl-bands", "trinity-three-stone"],
    rating: 4.9,
    reviewCount: 52,
    reviews: [
      r("Emily C.", "University Park", 5, "2026-05-30", "Wore them for my wedding", "Classic and modern at once. I'll wear them forever.", "14k Yellow Gold"),
      r("Sarah P.", "Austin", 5, "2026-03-14", "Lovely lustre", "Pearls are perfectly matched. Shipping was fast and insured."),
    ],
    images: { hero: "pearl-drops-1", model: "pearl-drops-2" },
    scaleMm: 24,
    added: "2025-03-30",
  },
  {
    slug: "dune-hoops",
    name: "Dune Hoops",
    category: "earrings",
    price: 1150,
    sku: "AL-A-405",
    metals: ["14k-yellow", "18k-yellow"],
    stone: "none",
    short: "Bold 30 mm hoops with a wide, softly flattened profile. Weight you can feel, never heavy.",
    long: [
      "Dune is a statement hoop made for daily wear: 30 mm across, 5 mm wide, hollow-formed so a pair weighs just under 6 grams.",
      "The flattened front catches wide sweeps of light, like sun across sand.",
    ],
    specs: [["Diameter", "30 mm"], ["Width", "5 mm"], ["Weight", "≈ 5.8 g per pair (14k)"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    collections: ["everyday-gold"],
    pairs: ["ember-wave", "droplet-snake", "olive-branch-cuff"],
    rating: 4.8,
    reviewCount: 41,
    reviews: [
      r("Maya J.", "Uptown", 5, "2026-08-11", "The perfect big hoop", "Light enough to wear all day, big enough to make a statement.", "14k Yellow Gold"),
      r("Carmen R.", "Oak Cliff", 5, "2026-04-04", "Obsessed", "Wearing them in every photo now."),
    ],
    images: { hero: "dune-hoops-1", model: "dune-hoops-2" },
    scaleMm: 30,
    added: "2025-05-18",
  },
  {
    slug: "constellation-climbers",
    name: "Constellation Climbers",
    category: "earrings",
    price: 520,
    sku: "AL-A-406",
    metals: ["14k-yellow", "14k-white"],
    stone: "opal",
    short: "Tiny opal marquises and white stones that climb the ear like a trail of leaves, on a single post.",
    long: [
      "Climbers trace the curve of the lobe upward, so one piercing looks like a curated ear. Opal marquises alternate with tiny white sapphires in graduated claws.",
      "Sold as a pair; ask in the showroom if you'd like a single.",
    ],
    specs: [["Stones", "Opal marquises, white sapphires"], ["Length", "16 mm"], ["Backs", "Push back"], ["Made in", "Dallas, TX"]],
    care: "Opal is delicate: keep it away from water, heat and perfume, and store it on its own.",
    soldOut: true,
    collections: ["new-in"],
    pairs: ["glint-studs", "sculpted-huggies", "lume-pendant"],
    rating: 4.7,
    reviewCount: 21,
    reviews: [
      r("Riley S.", "Dallas", 5, "2026-07-29", "Looks like three piercings", "Clever and pretty. Sold out for a reason.", "14k Yellow Gold"),
      r("Nina A.", "Plano", 4, "2026-06-06", "Delicate", "Very fine. Put them in carefully the first time."),
    ],
    images: { hero: "constellation-climbers-1", model: "constellation-climbers-2" },
    scaleMm: 16,
    added: "2026-08-15",
  },

  /* ------------------------------------------------------------ NECKLACES */
  {
    slug: "lume-pendant",
    name: "Lume Solitaire Pendant",
    category: "necklaces",
    price: 1280,
    sku: "AL-N-501",
    metals: ["14k-yellow", "14k-white", "14k-rose", "platinum"],
    lengths: [16, 18, 20],
    stones: ["lab", "natural"],
    naturalDelta: 1600,
    stone: "diamond",
    short: "A single 0.5 ct princess-cut diamond floating on a whisper-fine chain. The necklace you never take off.",
    long: [
      "The square diamond sits in a four-corner basket that slides freely, so it always finds the centre. The cable chain is fine but strong, with a spring ring we've tested to 4 kg.",
      "Every chain includes an extra jump ring two inches up, so an 18-inch chain also wears at 16.",
    ],
    specs: [["Stone", "0.5 ct princess cut, F / VS"], ["Chain", "1 mm cable"], ["Clasp", "Spring ring"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    badges: ["bestseller"],
    collections: ["bestsellers", "bridal"],
    pairs: ["glint-studs", "paperclip-chain", "tennis-bracelet"],
    rating: 4.9,
    reviewCount: 88,
    reviews: [
      r("Julia M.", "Highland Park", 5, "2026-07-15", "Floats like magic", "It really looks like the diamond is floating. Chain is so fine but hasn't tangled once.", "14k Yellow Gold · Lab-grown stone · 18″ chain"),
      r("Owen D.", "Richardson", 5, "2026-02-13", "Valentine's", "Wrapped beautifully, arrived in two days."),
    ],
    images: { hero: "lume-pendant-1", model: "lume-pendant-2" },
    scaleMm: 5.2,
    added: "2024-12-01",
  },
  {
    slug: "paperclip-chain",
    name: "Paperclip Chain",
    category: "necklaces",
    price: 740,
    sku: "AL-N-502",
    metals: ["14k-yellow", "14k-white", "14k-rose"],
    lengths: [16, 18, 20],
    stone: "none",
    short: "Long, flat links in solid gold. Wear it alone, layer it, or hang a pendant from any link.",
    long: [
      "Our paperclip chain uses 2.5 mm links, soldered closed one by one, with a lobster clasp large enough to open with one hand.",
      "Clip any of our pendants onto it, or wear two lengths together.",
    ],
    specs: [["Link", "2.5 × 7 mm paperclip"], ["Clasp", "Lobster"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    collections: ["everyday-gold"],
    pairs: ["noon-sun-pendant", "lume-pendant", "halo-hoops"],
    rating: 4.8,
    reviewCount: 72,
    reviews: [
      r("Bella G.", "Uptown", 5, "2026-06-23", "Layering staple", "Goes with everything I own. I bought a second length.", "14k Yellow Gold · 18″ chain"),
      r("Chloe H.", "Frisco", 5, "2026-01-20", "Solid", "Feels substantial, no kinks."),
    ],
    images: { hero: "paperclip-chain-1", model: "paperclip-chain-2" },
    scaleMm: 7,
    added: "2025-02-22",
  },
  {
    slug: "droplet-snake",
    name: "Droplet Snake Necklace",
    category: "necklaces",
    price: 980,
    sku: "AL-N-503",
    metals: ["14k-yellow", "18k-yellow"],
    lengths: [16, 18],
    stone: "none",
    short: "A polished gold droplet on a fluid snake chain that pours like water over the collarbone.",
    long: [
      "The droplet is hollow-formed and polished to a mirror, so it throws a little pool of light wherever you are. The snake chain is woven from tiny plates, which is why it moves like silk.",
      "Store it flat in the pouch provided and the chain will stay perfect for decades.",
    ],
    specs: [["Droplet", "14 mm, hollow-formed"], ["Chain", "1.2 mm snake"], ["Clasp", "Lobster"], ["Made in", "Dallas, TX"]],
    care: "Store flat and never knot it: snake chain can kink. Bring it in for a free professional clean any time.",
    sale: 0.2,
    collections: ["on-sale", "everyday-gold"],
    pairs: ["dune-hoops", "ember-wave", "olive-branch-cuff"],
    rating: 4.7,
    reviewCount: 34,
    reviews: [
      r("Vanessa L.", "Turtle Creek", 5, "2026-05-27", "Liquid gold", "The way the chain moves is unbelievable, and the droplet catches every light.", "14k Yellow Gold · 16″ chain"),
      r("Kim P.", "Plano", 4, "2026-03-09", "Stunning", "Gorgeous. Follow the storage tips!"),
    ],
    images: { hero: "herringbone-1", model: "herringbone-2" },
    scaleMm: 14,
    added: "2025-04-25",
  },
  {
    slug: "initial-tag",
    name: "Initial Tag Pendant",
    category: "necklaces",
    price: 180,
    sku: "AL-N-504",
    metals: ["sterling", "14k-yellow"],
    metalDelta: { "14k-yellow": 260 },
    lengths: [16, 18, 20],
    stone: "none",
    short: "A slim gold tag, engraved with one initial and set with a single tiny diamond, on a box chain.",
    long: [
      "Each tag is engraved by hand at the bench in our serif capital, then set with a 1.5 mm diamond above the letter.",
      "Tell us the initial in your order note or at checkout; we'll confirm by email before stamping.",
    ],
    specs: [["Tag", "8 × 16 mm"], ["Personalisation", "One hand-engraved initial"], ["Stone", "1.5 mm diamond"], ["Chain", "1 mm box"], ["Made in", "Dallas, TX"]],
    care: CARE_SILVER,
    badges: ["new"],
    collections: ["new-in", "gift-edit"],
    pairs: ["paperclip-chain", "thread-ring", "fine-id-bracelet"],
    rating: 4.8,
    reviewCount: 49,
    reviews: [
      r("Abby T.", "Mesquite", 5, "2026-09-16", "Bridesmaid gifts", "Ordered six with different initials. Each one came in its own box with a note.", "Sterling Silver · 18″ chain"),
      r("Grace W.", "Denton", 5, "2026-08-05", "Sweet and simple", "Perfect everyday piece."),
    ],
    images: { hero: "initial-disc-1", model: "initial-disc-2" },
    scaleMm: 16,
    added: "2026-08-28",
  },
  {
    slug: "pearl-strand",
    name: "Gulf Pearl Strand",
    category: "necklaces",
    price: 890,
    sku: "AL-N-505",
    metals: ["14k-yellow", "14k-white"],
    lengths: [16, 18],
    stone: "pearl",
    short: "A strand of 7 mm freshwater pearls, hand-knotted on silk, with a gold box clasp.",
    long: [
      "Every pearl is knotted individually on silk so that, if the strand ever breaks, you lose one pearl, not forty.",
      "Our pearls have a bright, near-white body with a soft rosé overtone. Restringing is free for two years.",
    ],
    specs: [["Pearls", "7–7.5 mm freshwater, AAA"], ["Knotting", "Hand-knotted silk"], ["Clasp", "Gold box clasp"], ["Made in", "Dallas, TX"]],
    care: CARE_PEARL,
    collections: ["bridal"],
    pairs: ["pearl-drops", "seed-pearl-bands", "glint-studs"],
    rating: 4.9,
    reviewCount: 29,
    reviews: [
      r("Margaret O.", "Highland Park", 5, "2026-04-18", "Graduation gift", "A grown-up first pearl necklace for my granddaughter. Beautiful knotting.", "14k Yellow Gold · 18″ chain"),
      r("Lily C.", "Allen", 5, "2026-02-02", "Timeless", "The lustre is amazing in sunlight."),
    ],
    images: { hero: "pearl-strand-1", model: "pearl-strand-2" },
    scaleMm: 7,
    added: "2025-06-01",
  },
  {
    slug: "noon-sun-pendant",
    name: "Noon Sun Pendant",
    category: "necklaces",
    price: 620,
    sku: "AL-N-506",
    metals: ["14k-yellow", "14k-rose"],
    lengths: [18, 20],
    stone: "none",
    short: "An open sunburst of baguette-cut stones around a ring of gold: our midday sun, 15 mm across.",
    long: [
      "Twelve tiny baguettes radiate from an open circle, each in its own claw, so light passes straight through the middle of the sun.",
      "Pairs beautifully with a second, shorter chain.",
    ],
    specs: [["Pendant", "15 mm open sunburst"], ["Stones", "12 white sapphire baguettes"], ["Chain", "1 mm cable"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    collections: ["everyday-gold"],
    pairs: ["paperclip-chain", "halo-hoops", "knot-link"],
    rating: 4.8,
    reviewCount: 26,
    reviews: [
      r("Harper J.", "Lakewood", 5, "2026-07-03", "Little piece of sunshine", "Bought for my mom, who calls everything good her sunshine. Perfect.", "14k Yellow Gold · 18″ chain"),
      r("Elena V.", "Dallas", 5, "2026-05-05", "Gorgeous detail", "The little baguettes sparkle so much."),
    ],
    images: { hero: "sun-medallion-1", model: "sun-medallion-2" },
    scaleMm: 15,
    added: "2025-09-01",
  },

  /* ------------------------------------------------------------ BRACELETS */
  {
    slug: "tennis-bracelet",
    name: "Lume Tennis Bracelet",
    category: "bracelets",
    price: 3200,
    sku: "AL-B-601",
    metals: ["14k-white", "platinum"],
    stones: ["lab", "natural"],
    naturalDelta: 4200,
    stone: "diamond",
    short: "Three carats of round diamonds in four-claw links, with a double-locking box clasp.",
    long: [
      "Each link is articulated so the bracelet drapes like fabric. Price shown is for 3 ct of lab diamonds, F–G / VS, in a 7-inch length.",
      "The box clasp has two independent safety catches. We check every link under magnification before it ships.",
    ],
    specs: [["Stones", "≈ 52 × 2.5 mm round, 3.0 ct"], ["Length", "7 in (6.5 / 7.5 on request)"], ["Clasp", "Box clasp, double safety"], ["Made in", "Dallas, TX"]],
    care: CARE_STONE,
    badges: ["bestseller"],
    collections: ["bestsellers", "bridal"],
    pairs: ["glint-studs", "lume-pendant", "eternity-band"],
    rating: 5,
    reviewCount: 47,
    reviews: [
      r("Monica F.", "Preston Hollow", 5, "2026-08-20", "Wow", "Bought it for myself after closing my first big deal. Zero regrets.", "14k White Gold · Lab-grown stone"),
      r("Jason L.", "Southlake", 5, "2026-04-29", "Anniversary", "The clasp is solid. Wife wears it daily."),
    ],
    images: { hero: "tennis-bracelet-1", model: "tennis-bracelet-2" },
    scaleMm: 2.5,
    added: "2025-01-25",
  },
  {
    slug: "olive-branch-cuff",
    name: "Olive Branch Cuff",
    category: "bracelets",
    price: 980,
    sku: "AL-B-602",
    metals: ["14k-yellow", "18k-yellow", "sterling"],
    metalDelta: { sterling: -640 },
    stone: "none",
    short: "An open cuff of two olive branches, each leaf carved by hand, that slides on from the side of the wrist.",
    long: [
      "Margot carved the leaves from a cutting in her own Lakewood garden. The fine wire band has a gentle spring, so it stays put without a clasp.",
      "Peace, in gold. A favourite for anniversaries and new beginnings.",
    ],
    specs: [["Leaves", "Hand-carved, 9 per branch"], ["Wire", "1.6 mm"], ["Fit", "Medium (fits 6–6.75 in wrists)"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    collections: ["everyday-gold"],
    pairs: ["dune-hoops", "ember-wave", "knot-link"],
    rating: 4.8,
    reviewCount: 23,
    reviews: [
      r("Tara B.", "Knox-Henderson", 5, "2026-06-18", "Sculptural", "Like wearing a small sculpture. Stays put and gets noticed.", "14k Yellow Gold"),
      r("Paige K.", "Plano", 4, "2026-02-27", "Great sterling option", "Started with silver, upgrading soon."),
    ],
    images: { hero: "cuff-bangle-1", model: "cuff-bangle-2" },
    scaleMm: 22,
    added: "2025-03-03",
  },
  {
    slug: "fine-id-bracelet",
    name: "Fine ID Bracelet",
    category: "bracelets",
    price: 180,
    sku: "AL-B-603",
    metals: ["sterling", "14k-yellow", "14k-rose"],
    metalDelta: { "14k-yellow": 150, "14k-rose": 150 },
    stone: "none",
    short: "A slim gold ID plate on a barely-there chain, ready for a name, a date or nothing at all.",
    long: [
      "Our lightest piece and our most popular gift: a softly curved 25 mm plate on a 1 mm cable chain, with jump rings at 6, 6.5 and 7 inches.",
      "Add hand engraving in the cart. In sterling it's under $200; in solid gold it's forever.",
    ],
    specs: [["Plate", "25 × 6 mm, engravable"], ["Chain", "1 mm cable"], ["Fit", "6–7 in"], ["Made in", "Dallas, TX"]],
    care: CARE_SILVER,
    collections: ["gift-edit", "everyday-gold"],
    pairs: ["thread-ring", "onyx-station", "initial-tag"],
    rating: 4.7,
    reviewCount: 81,
    reviews: [
      r("Kennedy R.", "Arlington", 5, "2026-09-06", "Perfect stacker", "Wear it with my watch every day.", "14k Yellow Gold"),
      r("Lucy A.", "Irving", 5, "2026-04-15", "Great gift", "Bought five for my team with their initials engraved. Everyone loved them."),
    ],
    images: { hero: "fine-chain-bracelet-1", model: "fine-chain-bracelet-2" },
    scaleMm: 1,
    added: "2025-02-14",
  },
  {
    slug: "knot-link",
    name: "Knot Link Bracelet",
    category: "bracelets",
    price: 1350,
    sku: "AL-B-604",
    metals: ["14k-yellow", "14k-white"],
    stone: "none",
    short: "Long, polished links tied with little gold knots. Substantial, playful, built to be inherited.",
    long: [
      "Every other link is a hand-tied knot of solid gold wire, soldered closed so it can never come undone.",
      "A lobster clasp at one end and a 1-inch extender at the other let it fit almost any wrist.",
    ],
    specs: [["Link", "6 mm oval + knot"], ["Length", "6.5 in + 1 in extender"], ["Clasp", "Lobster"], ["Made in", "Dallas, TX"]],
    care: CARE_GOLD,
    collections: ["everyday-gold"],
    pairs: ["forge-band", "lume-signet", "olive-branch-cuff"],
    rating: 4.9,
    reviewCount: 30,
    reviews: [
      r("Marcus L.", "Las Colinas", 5, "2026-07-21", "Proper weight", "Exactly what I wanted: solid, with a bit of personality.", "14k Yellow Gold"),
      r("Ruth E.", "Dallas", 5, "2026-01-06", "Gift for my son", "He wears it every day."),
    ],
    images: { hero: "curb-link-1", model: "curb-link-2" },
    scaleMm: 6,
    added: "2025-06-20",
  },
  {
    slug: "onyx-station",
    name: "Onyx Station Bracelet",
    category: "bracelets",
    price: 690,
    sku: "AL-B-605",
    metals: ["14k-yellow", "14k-white", "14k-rose"],
    stone: "onyx",
    short: "Black onyx discs in gold frames, spaced along a curb chain like stations at night.",
    long: [
      "Three polished onyx discs sit in gold frames along a diamond-cut curb chain: graphic, quiet, and lovely against a tan.",
      "Adjustable from 6.5 to 7.5 inches with two jump rings.",
    ],
    specs: [["Stations", "3 × 9 mm black onyx"], ["Chain", "3 mm curb"], ["Fit", "6.5–7.5 in"], ["Made in", "Dallas, TX"]],
    care: "Onyx is soft compared with diamond: keep it away from knocks and harsh cleaners, and wipe it with a damp cloth.",
    sale: 0.15,
    collections: ["on-sale"],
    pairs: ["fine-id-bracelet", "glint-studs", "lume-pendant"],
    rating: 4.8,
    reviewCount: 38,
    reviews: [
      r("Danielle M.", "Plano", 5, "2026-08-09", "Graphic and chic", "Exactly the right amount of contrast for work. Looks great with my watch.", "14k Yellow Gold"),
      r("Hope S.", "Frisco", 5, "2026-03-31", "Great on sale", "Caught it on sale, couldn't be happier."),
    ],
    images: { hero: "station-bracelet-1", model: "station-bracelet-2" },
    scaleMm: 9,
    added: "2025-07-30",
  },
];

export const productBySlug = Object.fromEntries(products.map((p) => [p.slug, p])) as Record<string, Product>;
