/*
 * Art direction for scripts/process-images.mjs.
 * crops: zoom (1 = largest 4:5 window), cx/cy = centre as a fraction of the source.
 */
export const crops = {
  // rings
  "lume-signet-1": { zoom: 1.5, cx: 0.56, cy: 0.5 },
  "thread-ring-1": { zoom: 2.4, cx: 0.5, cy: 0.5 },
  "ember-dome-1": { zoom: 1.05, cx: 0.5, cy: 0.5 },
  "meridian-pave-1": { zoom: 1.6, cx: 0.47, cy: 0.5 },
  "solene-emerald-1": { zoom: 1.7, cx: 0.56, cy: 0.5 },
  "dusk-sapphire-1": { zoom: 1.7, cx: 0.48, cy: 0.5 },
  "twin-pearl-1": { zoom: 1.5, cx: 0.42, cy: 0.56 },
  "ardley-solitaire-1": { zoom: 1.25, cx: 0.5, cy: 0.55 },
  "celeste-oval-halo-1": { zoom: 2.3, cx: 0.5, cy: 0.5 },
  "trinity-three-stone-1": { zoom: 1.15, cx: 0.5, cy: 0.55 },
  "trinity-three-stone-2": { zoom: 1.5, cx: 0.36, cy: 0.62 },
  "margot-emerald-cut-1": { zoom: 1.25, cx: 0.5, cy: 0.5 },
  "dewdrop-pear-1": { zoom: 1.2, cx: 0.5, cy: 0.5 },
  "aurora-hidden-halo-1": { zoom: 1.35, cx: 0.6, cy: 0.5, tone: "yellow" },
  "classic-band-1": { zoom: 1.05, cx: 0.5, cy: 0.5 },
  "knife-edge-band-1": { zoom: 1.35, cx: 0.5, cy: 0.62 },
  "eternity-band-1": { zoom: 1.2, cx: 0.5, cy: 0.55 },
  "hammered-band-1": { zoom: 1.5, cx: 0.5, cy: 0.72 },
  "contour-band-1": { zoom: 1.3, cx: 0.5, cy: 0.5 },
  // earrings, necklaces, bracelets
  "constellation-climbers-1": { zoom: 1.05, cx: 0.5, cy: 0.5 },
  "glint-studs-1": { zoom: 1.5, cx: 0.48, cy: 0.58 },
  "glint-studs-2": { zoom: 1.2, cx: 0.55, cy: 0.5 },
  "dune-hoops-1": { zoom: 1.1, cx: 0.5, cy: 0.5 },
  "halo-hoops-1": { zoom: 1.45, cx: 0.48, cy: 0.5 },
  "pearl-drops-1": { zoom: 1.2, cx: 0.48, cy: 0.5 },
  "sculpted-huggies-1": { zoom: 1.35, cx: 0.5, cy: 0.48 },
  "herringbone-1": { zoom: 1.05, cx: 0.5, cy: 0.5 },
  "initial-disc-1": { zoom: 1.1, cx: 0.5, cy: 0.55 },
  "lume-pendant-1": { zoom: 1.25, cx: 0.45, cy: 0.58 },
  "paperclip-chain-1": { zoom: 1.45, cx: 0.55, cy: 0.72 },
  "pearl-strand-1": { zoom: 1.1, cx: 0.58, cy: 0.5 },
  "sun-medallion-1": { zoom: 1.35, cx: 0.45, cy: 0.45 },
  "cuff-bangle-1": { zoom: 1.2, cx: 0.5, cy: 0.5 },
  "curb-link-1": { zoom: 1.1, cx: 0.5, cy: 0.5 },
  "fine-chain-bracelet-1": { zoom: 1.1, cx: 0.5, cy: 0.5 },
  "station-bracelet-1": { zoom: 1.05, cx: 0.5, cy: 0.5 },
  "tennis-bracelet-1": { zoom: 1.05, cx: 0.5, cy: 0.5, tone: "white" },
  "tennis-bracelet-2": { zoom: 1.3, cx: 0.6, cy: 0.38 },
  // scenes with an explicit crop
  "hero-portrait": { aspect: 0.62, zoom: 1, cx: 0.4, cy: 0.5 },
};

/** Scene max dimension (px). Heroes are bigger; everything else 2000. */
export const sceneSizes = {
  "hero-a": 2560,
  "hero-b": 2560,
  "hero-c": 2560,
  "hero-portrait": 1400,
  "dallas-street": 2400,
  "texture-gold": 1600,
};

export const alts = {
  "hero-a": "Two arms reaching across black silk, wearing fine gold chain bracelets and stacked rings",
  "hero-b": "A princess-cut diamond solitaire stacked with gold bands, caught in a single beam of warm light",
  "hero-portrait": "A princess-cut diamond solitaire stacked with gold bands, caught in a single beam of warm light",
  "hero-c": "An open hand, palm up, wearing slim bands in warm side light",
  "macro-facets": "A loose round brilliant diamond resting on dark bark, its facets catching the light",
  "macro-gem": "Extreme close-up of a checkerboard-cut yellow gemstone held in gold claws",
  caustics: "Ribbed glass tumblers throwing golden caustic light across a cream table",
  "still-stone": "Fine gold necklaces, rings and earrings scattered across a slab of grey stone",
  "still-linen": "A diamond-set gold band resting in the folds of a soft taupe knit",
  "still-water": "A diamond solitaire resting in a narrow channel of rippling water cut into pale stone",
  "step-sketch": "A designer holding a sheet of hand-drawn jewelry sketches",
  "step-wax": "Hands carving a green wax ring model at the bench",
  "step-casting": "Molten metal pouring from a glowing crucible in a shower of sparks",
  "step-setting": "A setter wearing a magnifier, setting a stone into a ring with a fine tool",
  "step-polish": "Hands pressing a ring against a spinning polishing wheel",
  "bench-hands": "A jeweler's weathered hands holding a ring and a tool over the bench",
  "bench-tools": "A steel ring mandrel with a gold band, a micrometer and a loupe on a dark bench",
  "bench-flame": "A small torch flame heating a ring held in a soldering stand",
  showroom: "Cream wall shelving displaying gold necklaces, bracelets and earrings in soft light",
  "showroom-2": "A calm consultation corner with a glowing round wall light and a cream sofa",
  "dallas-street": "The Dallas skyline at dusk reflected in the Trinity River",
  "dallas-street-b": "A tree-lined Dallas sidewalk with red-framed shop windows",
  "couple-hands": "A woman's hand with a slim diamond ring resting on her partner's hand with a wedding band",
  proposal: "A man sliding an engagement ring onto his partner's finger in warm evening light",
  "gift-box": "A gold ring with small stones in an open charcoal ring box",
  "model-1": "Fine gold chains with small pendants on a collarbone, lit by a streak of sun",
  "model-2": "A woman in a white ribbed tank wearing large sculptural gold hoop earrings",
  "model-3": "A woman in a black blazer wearing sculptural gold leaf earrings",
  "model-4": "A man in a black tee wearing a gold rope chain",
  "men-ring": "A man's hand resting on a wooden chair, wearing a band",
  "texture-gold": "Abstract texture of crumpled gold leaf",
  "hand-scale-a": "A relaxed hand, fingers slightly spread, against a plain grey background",
  "hand-scale-b": "A relaxed hand extended against a warm beige background",
};
